language: node_js
node_js:
  - lts/*

cache: npm

jobs:
  include:
    - stage: test-e2e
      before_script:
        - docker run -d --name mongo-local -p 27017:27017  mongo
      script:
        - npm run test:e2e
